# See. https://scala-cli.virtuslab.org/docs/cookbooks/gh-action#run-tests-in-github-ci
name: Scala CLI CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: coursier/cache-action@v6.3
      - uses: VirtusLab/scala-cli-setup@v0.1
      - run: scala-cli test .
